name: Project setup

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@master
            -   uses: actions/checkout@v1
                with:
                    repository: shopware/platform
                    ref: refs/heads/master
            -   name: start setup proccess
                run: php ./psh.phar docker:start

            -   name: docker init
                run: php ./psh.phar docker:init-data
            -   name: Install dependencies
                run: docker exec  shopware6-development_app_server_1 php psh.phar install
            -   name: Run tests
                run: docker exec  shopware6-development_app_server_1 php psh.phar unit
