name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/checkout@v1
      with: 
        repository: shopware/platform
        ref: refs/heads/master
    - name: start setup proccess
      run: php ./psh.phar docker:start

    - name: docker init
      run: php ./psh.phar docker:init

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
